"use client";
import { useState } from "react";

type Transaction = { id: number; date: string; description: string; category: string; account: string; type: "Receita" | "Despesa"; value: number };
const initial: Transaction[] = [
  { id: 1, date: "05/10/2026", description: "Supermercado", category: "Alimentação", account: "Nubank", type: "Despesa", value: 980.4 },
  { id: 2, date: "01/10/2026", description: "Salário", category: "Renda", account: "Nubank", type: "Receita", value: 8500 },
];
export function TransactionsPanel() { const [items,setItems]=useState(initial); const [term,setTerm]=useState(""); const [kind,setKind]=useState("Todos"); const rows=items.filter(x=>(kind==="Todos"||x.type===kind)&&x.description.toLowerCase().includes(term.toLowerCase())); return <section><div className="mb-5 flex gap-3"><input value={term} onChange={e=>setTerm(e.target.value)} placeholder="Buscar lançamento" className="rounded-xl border bg-white px-4 py-2.5 text-sm"/><select value={kind} onChange={e=>setKind(e.target.value)} className="rounded-xl border bg-white px-3 text-sm"><option>Todos</option><option>Receita</option><option>Despesa</option></select></div><div className="overflow-hidden rounded-2xl border bg-white"><div className="grid grid-cols-[110px_1fr_140px_140px_140px_32px] bg-slate-50 px-5 py-3 text-xs font-semibold uppercase text-slate-400"><span>Data</span><span>Descrição</span><span>Categoria</span><span>Conta</span><span>Valor</span><span/></div>{rows.map(x=><div key={x.id} className="grid grid-cols-[110px_1fr_140px_140px_140px_32px] border-t px-5 py-4 text-sm"><span>{x.date}</span><b>{x.description}</b><span>{x.category}</span><span>{x.account}</span><b className={x.type==="Receita"?"text-emerald-600":"text-rose-600"}>{x.type==="Receita"?"+":"-"} R$ {x.value.toLocaleString("pt-BR",{minimumFractionDigits:2})}</b><button onClick={()=>setItems(items.filter(i=>i.id!==x.id))} className="text-slate-400">×</button></div>)}{!rows.length&&<p className="p-8 text-center text-slate-500">Nenhum lançamento encontrado.</p>}</div></section> }
