create extension if not exists pgcrypto;

create type public.transaction_type as enum ('income','expense','transfer');
create type public.transaction_status as enum ('pending','paid','overdue','received','to_receive','cancelled');
create type public.account_type as enum ('checking','savings','cash','digital_wallet','investment','other');
create type public.invoice_status as enum ('open','closed','paid');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text, avatar_url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.accounts (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, institution text, type public.account_type not null default 'checking', opening_balance numeric(14,2) not null default 0, color text, is_active boolean not null default true, created_at timestamptz not null default now());
create table public.categories (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, icon text, color text, kind public.transaction_type, created_at timestamptz not null default now(), unique(user_id,name));
create table public.credit_cards (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, bank text, credit_limit numeric(14,2) not null check (credit_limit >= 0), closing_day smallint not null check (closing_day between 1 and 31), due_day smallint not null check (due_day between 1 and 31), color text, is_active boolean not null default true, created_at timestamptz not null default now());
create table public.transactions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, description text not null, amount numeric(14,2) not null check (amount > 0), type public.transaction_type not null, status public.transaction_status not null default 'pending', transaction_date date not null default current_date, due_date date, paid_at timestamptz, account_id uuid references public.accounts(id) on delete set null, destination_account_id uuid references public.accounts(id) on delete set null, category_id uuid references public.categories(id) on delete set null, payment_method text, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check ((type <> 'transfer') or (account_id is not null and destination_account_id is not null and account_id <> destination_account_id)));
create table public.credit_card_invoices (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, credit_card_id uuid not null references public.credit_cards(id) on delete cascade, reference_month date not null, status public.invoice_status not null default 'open', due_date date, paid_at timestamptz, payment_account_id uuid references public.accounts(id) on delete set null, unique(credit_card_id,reference_month));
create table public.credit_card_transactions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, credit_card_id uuid not null references public.credit_cards(id) on delete cascade, invoice_id uuid references public.credit_card_invoices(id) on delete set null, category_id uuid references public.categories(id) on delete set null, description text not null, amount numeric(14,2) not null check(amount > 0), transaction_date date not null default current_date, installments smallint not null default 1 check(installments > 0), created_at timestamptz not null default now());
create table public.installments (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, credit_card_transaction_id uuid not null references public.credit_card_transactions(id) on delete cascade, invoice_id uuid references public.credit_card_invoices(id) on delete set null, installment_number smallint not null, total_installments smallint not null, amount numeric(14,2) not null, due_date date not null, unique(credit_card_transaction_id,installment_number));
create table public.recurring_transactions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, description text not null, amount numeric(14,2) not null, type public.transaction_type not null, frequency text not null check(frequency in ('weekly','monthly','yearly','custom')), next_run date not null, account_id uuid references public.accounts(id) on delete set null, category_id uuid references public.categories(id) on delete set null, is_active boolean not null default true, created_at timestamptz not null default now());
create table public.budgets (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, reference_month date not null, created_at timestamptz not null default now(), unique(user_id,reference_month));
create table public.budget_categories (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, budget_id uuid not null references public.budgets(id) on delete cascade, category_id uuid not null references public.categories(id) on delete cascade, amount numeric(14,2) not null check(amount >= 0), unique(budget_id,category_id));
create table public.transaction_attachments (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, transaction_id uuid not null references public.transactions(id) on delete cascade, storage_path text not null, file_name text not null, created_at timestamptz not null default now());

create index transactions_user_date_idx on public.transactions(user_id,transaction_date desc); create index transactions_user_status_idx on public.transactions(user_id,status); create index accounts_user_idx on public.accounts(user_id); create index categories_user_idx on public.categories(user_id); create index card_transactions_user_idx on public.credit_card_transactions(user_id);
alter table public.profiles enable row level security; alter table public.accounts enable row level security; alter table public.categories enable row level security; alter table public.credit_cards enable row level security; alter table public.transactions enable row level security; alter table public.credit_card_invoices enable row level security; alter table public.credit_card_transactions enable row level security; alter table public.installments enable row level security; alter table public.recurring_transactions enable row level security; alter table public.budgets enable row level security; alter table public.budget_categories enable row level security; alter table public.transaction_attachments enable row level security;
do $$ declare t text; begin foreach t in array array['profiles','accounts','categories','credit_cards','transactions','credit_card_invoices','credit_card_transactions','installments','recurring_transactions','budgets','budget_categories','transaction_attachments'] loop execute format('create policy "user owns %1$s" on public.%1$I for all using (auth.uid() = user_id) with check (auth.uid() = user_id)',t); end loop; end $$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.profiles(id,full_name) values(new.id,coalesce(new.raw_user_meta_data->>'full_name','')); return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
